# Generated by Django 5.0 on 2023-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_toollink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
