# Generated by Django 5.0 on 2024-04-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_users_employee_id_users_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
