# Generated by Django 5.0 on 2024-04-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_token',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
