# Generated by Django 5.0.4 on 2026-01-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
