# Generated by Django 5.0.4 on 2026-01-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
